services:
  - type: web
    name: techfuturists
    runtime: python
    repo: https://github.com/RicheTheDev/TechFuturists
    branch: main
    buildCommand: |
      pip install -r requirements.txt
      flask db upgrade || echo "Migration skipped (SQLite)"
    startCommand: python3 run.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        sync: false
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
    autoDeploy: true
