databases:
  - name: techfuturists-db
    databaseName: techfuturists
    user: techfuturists_user

services:
  - type: web
    name: techfuturists
    runtime: python
    repo: https://github.com/RicheTheDev/TechFuturists
    branch: main
    buildCommand: |
      pip install -r requirements.txt
      flask db upgrade
    startCommand: python3 run.py
    envVars:
      - key: DATABASE_URL
        value: postgresql://postgres:Ulrich_@2025@db.hmptliikznipedvucvwp.supabase.co:5432/postgres
        sync: false
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        sync: false
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
    autoDeploy: true
